stages:
  get_raw_data_taxa:
    cmd: python pipeline/s0.0_get_raw_data_taxa.py
    deps:
    - pipeline/s0.0_get_raw_data_taxa.py
    outs:
    - ./data/taxa.parquet
    params:
    - get_raw_data_taxa.max_16s_len
    - get_raw_data_taxa.min_16s_len
    metrics:
    - ./data/metrics/s0.0_metrics.yaml:
        cache: false
    frozen: true
  get_raw_data_proteins:
    cmd: python pipeline/s0.1_get_raw_data_proteins.py
    deps:
    - ./pipeline/s0.1_get_raw_data_proteins.py
    outs:
    - ./data/uniprot/uniprot_pulled_timestamp
    params:
    - get_raw_data_proteins.dev_only_one_uniprot_file
    metrics:
    - ./data/metrics/s0.1_metrics.yaml:
        cache: false
    frozen: true
  get_proteome_mdata:
    cmd: python pipeline/s0.2_get_proteome_mdata.py
    deps:
    - pipeline/s0.2_get_proteome_mdata.py
    outs:
    - ./data/uniprot/proteome_metadata.csv
    frozen: true
  parse_proteins:
    cmd: python pipeline/s0.3_parse_proteins.py
    deps:
    - ./data/taxa.parquet
    - ./data/uniprot/proteome_metadata.csv
    - ./data/uniprot/uniprot_pulled_timestamp
    - ./learn2therm/io.py
    - ./pipeline/s0.3_parse_proteins.py
    outs:
    - ./data/metrics/s0.3_protein_per_data_distr.csv
    - ./data/proteins/
    params:
    - parse_proteins.dev_only_one_uniprot_file
    - parse_proteins.max_prot_per_file
    metrics:
    - ./data/metrics/s0.3_metrics.yaml:
        cache: false
    frozen: true
  label_taxa:
    cmd: python pipeline/s1.0_label_taxa.py
    deps:
    - ./data/taxa.parquet
    - ./learn2therm/utils.py
    - pipeline/s1.0_label_taxa.py
    params:
    - label_taxa.ogt_threshold
    outs:
    - ./data/taxa_thermophile_labels.parquet
    metrics:
    - ./data/metrics/s1.0_metrics.yaml:
        cache: false
    plots:
    - ./data/plots/ogt_hist.png:
        cache: false
  get_16s_blast_scores:
    cmd: python pipeline/s1.1_get_16s_blast_scores.py
    deps:
    - ./data/metrics/s0.3_protein_per_data_distr.csv
    - ./data/taxa.parquet
    - ./data/taxa_thermophile_labels.parquet
    - ./learn2therm/blast.py
    - ./learn2therm/io.py
    - ./learn2therm/utils.py
    - ./pipeline/s1.1_get_16s_blast_scores.py
    outs:
    - ./data/taxa_pairs/alignment/
    params:
    - get_16s_blast_scores.blast_metrics
    - get_16s_blast_scores.dev_n_sample
    - get_16s_blast_scores.gapextend_penalty
    - get_16s_blast_scores.gapopen_penalty
    - get_16s_blast_scores.num_threads
    - get_16s_blast_scores.penalty
    - get_16s_blast_scores.reward
    - get_16s_blast_scores.ungapped
    - get_16s_blast_scores.word_size
    metrics:
    - ./data/metrics/s1.1_metrics.yaml:
        cache: false

    frozen: true
  label_all_pairs:
    cmd: python pipeline/s1.2_label_all_pairs.py
    deps:
    - ./data/taxa_pairs/alignment
    - ./learn2therm/utils.py
    - ./pipeline/s1.2_label_all_pairs.py
    outs:
    - ./data/taxa_pairs/pair_labels
    params:
    - label_all_pairs.blast_metric_thresholds
    - label_all_pairs.dev_only_one_file
    metrics:
    - ./data/metrics/s1.2_metrics.yaml:
        cache: false
    frozen: true
  protein_alignment:
    cmd: python ./pipeline/s1.3_protein_alignment.py
    deps:
    - ./data/proteins
    - ./data/taxa_pairs/alignment
    - ./data/taxa_pairs/pair_labels
    - ./learn2therm/blast.py
    - ./pipeline/s1.3_protein_alignment.py
    params:
    - get_protein_blast_scores.dask_cluster_class
    - get_protein_blast_scores.dev_sample_pairs
    - get_protein_blast_scores.max_protein_length
    - get_protein_blast_scores.method
    - get_protein_blast_scores.method_blast_params
    - get_protein_blast_scores.method_diamond_params
    - get_protein_blast_scores.n_jobs
    - get_protein_blast_scores.save_frequency
    outs:
    - ./data/protein_pairs/:
        checkpoint: true
    metrics:
    - ./data/metrics/s1.3_metrics.yaml:
        cache: false
        persist: true
  make_database:
    cmd: python ./pipeline/s1.4_make_database.py
    deps:
    - ./data/proteins
    - ./data/taxa.parquet
    - ./data/taxa_thermophile_labels.parquet
    - ./data/taxa_pairs/alignment
    - ./data/taxa_pairs/pair_labels
    - ./data/protein_pairs
    - ./learn2therm/database.py
    outs:
    - ./data/database.ddb
  get_hait_pairs:
    cmd: python ./pipeline/s2.1_get_hait_pairs.py
    deps:
    - ./pipeline/s2.1_get_hait_pairs.py
    outs:
    - ./data/validation/hait_pairs.csv
  compare_to_Tm:
    cmd: python ./pipeline/s2.2_compare_to_Tm.py
    deps:
    - ./data/proteins
    - ./data/taxa.parquet
    - ./pipeline/s2.2_compare_to_Tm.py
    outs:
    - ./data/validation/tm/ogt_vs_tm.csv
    metrics:
    - ./data/validation/tm/metrics.yaml:
        cache: false
    plots:
    - ./data/validation/tm/ogt_vs_tm_check.png:
        cache: false
  run_hait_alignment:
    cmd: python ./pipeline/s2.3_run_hait_alignment.py
    deps:
    - ./pipeline/s2.3_run_hait_alignment.py
    - ./learn2therm/blast.py
    - ./data/validation/hait_pairs.csv
    outs:
    - ./data/validation/hait_aligned_scores.csv
    params:
    - get_protein_blast_scores.method
    - get_protein_blast_scores.method_blast_params
    - get_protein_blast_scores.method_diamond_params
  compare_hait_alignment:
    cmd: python ./pipeline/s2.4_compare_hait_alignment.py
    deps:
    - ./pipeline/s2.4_compare_hait_alignment.py
    - ./data/validation/hait_aligned_scores.csv
    - ./data/database.ddb
    plots:
    - ./data/validation/hait_alignment/:
        cache: false

  get_HMM_profiles:
    cmd: python ./pipeline/s2.5_get_HMM_profiles.py
    outs:
    - ./data/validation/hmmer/Pfam-A.hmm
    metrics:
    - ./data/validation/hmmer/s2.5_metrics.yaml:
        cache: false
  hmmer_hait:
    cmd: python ./pipeline/s2.6_hmmer_hait.py
    deps:
    - ./pipeline/s2.6_hmmer_hait.py
    - ./data/validation/hmmer/Pfam-A.hmm
    - ./data/validation/hait_pairs.csv
    - ./learn2therm/hmmer.py
    outs:
    - ./data/validation/hmmer/hait_scores.csv
    params:
    - run_hmmer.e_value
    - run_hmmer.njobs
    - run_hmmer.jaccard_threshold
    plots:
    - ./data/validation/hmmer/hait_jaccard.png:
        cache: false
    metrics:
    - ./data/validation/hmmer/s2.6_metrics.yaml:
        cache: false
  run_hmmer:
    cmd: python ./pipeline/s2.7_run_hmmer.py
    deps:
    - ./pipeline/s2.7_run_hmmer.py
    - ./data/validation/hmmer/Pfam-A.hmm
    - ./data/database.ddb
    - ./learn2therm/hmmer.py
    outs:
    - ./data/validation/hmmer/hmmer_outputs/
    params:
    - run_hmmer.e_value
    - run_hmmer.njobs
    - run_hmmer.chunk_size
    - run_hmmer.scan
    - run_hmmer.dev_sample_data
    - run_hmmer.prefetch
    metrics:
    - ./data/validation/hmmer/s2.7_metrics.yaml:
        cache: false
  # parse_hmmer_result:
  #   cmd: python ./pipeline/s2.8_parse_hmmer_result.py
  #   deps:
  #   - ./pipeline/s2.8_parse_hmmer_result.py
  #   - ./data/validation/hmmer/hmmer_outputs/
  #   - ./learn2therm/hmmer.py
  #   - ./data/protein_pairs/
  #   outs:
  #   - ./data/validation/hmmer/hmmer_labels/
  #   params:
  #   - run_hmmer.jaccard_threshold
  #   - run_hmmer.chunk_size
  #   metrics:
  #   - ./data/validation/hmmer/s2.8_metrics.yaml:
  #       cache: false

