stages:
  get_ncbi_refseq:
    cmd: bash pipeline/s0.0_get_ncbi_refseq.sh
    deps:
    - pipeline/s0.0_get_ncbi_refseq.sh
    outs:
    - ./data/refseq
  get_bacdive_ogt:
    cmd: python pipeline/s0.1_get_bacdive_ogt.py
    deps:
    - pipeline/s0.1_get_bacdive_ogt.py
    - ./data/refseq
    outs:
    - ./data/taxa/taxa_info_and_ogt.csv
    params:
    - ./pipeline/s0_data_extraction_params.yaml:
      - get_bacdive_ogt.n_jobs
      - get_bacdive_ogt.n_sample
    metrics:
    - ./data/metrics/s0.1_metrics.yaml:
        cache: false
  label_taxa:
    cmd: python pipeline/s1.0_label_taxa.py
    deps:
    - pipeline/s1.0_label_taxa.py
    - ./data/taxa/taxa_info_and_ogt.csv
    params:
    - ./pipeline/s1_data_processing_params.yaml:
      - label_taxa.ogt_threshold
      - label_taxa.ogt_determination_method
    outs:
    - ./data/taxa/labels.csv
    metrics:
    - ./data/metrics/s1.0_metrics.yaml:
        cache: false
    plots:
    - ./data/plots/ogt_hist.png:
        cache: false
  get_proteins:
    cmd: python pipeline/s1.1_get_protein_sequences.py
    deps:
    - pipeline/s1.1_get_protein_sequences.py
    - ./data/refseq
    - ./data/taxa/taxa_info_and_ogt.csv
    outs:
    - ./data/taxa/16s_rRNA.csv
    - ./data/taxa/proteins.csv
    params:
    - ./pipeline/s1_data_processing_params.yaml:
      - get_protein_sequences.n_jobs
      - get_protein_sequences.n_sample
    metrics:
    - ./data/metrics/s1.1_metrics.yaml:
        cache: false
  get_16s_blast_scores:
    cmd: python pipeline/s1.2_get_16s_blast_scores.py
    deps:
    - ./pipeline/s1.2_get_16s_blast_scores.py
    - ./data/taxa/labels.csv
    - ./data/taxa/16s_rRNA.csv
    outs:
    - ./data/taxa_pairs/pairwise_16s_blast.csv
    params:
    - ./pipeline/s1_data_processing_params.yaml:
      - get_16s_blast_scores.n_jobs
      - get_16s_blast_scores.word_size
      - get_16s_blast_scores.gapopen_penalty
      - get_16s_blast_scores.gapextend_penalty
      - get_16s_blast_scores.reward
      - get_16s_blast_scores.penalty
      - get_16s_blast_scores.ungapped
      - get_16s_blast_scores.n_sample
      - get_16s_blast_scores.blast_metrics
