name: learn2thermDB
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - biopython=1.79
  - dask=2022.2.1
  - dask-jobqueue=0.8.1
  - distributed=2022.2.1
  - joblib
  - dvc
  - dvc-data
  - dvc-ssh
  - matplotlib
  - pandas
  - python=3.9
  - pyyaml
  - seaborn
  - matplotlib
  - blast
  - diamond
  - pyarrow
  - fastparquet
  - pip
  - pip:
    - duckdb==0.7.1
    - codecarbon==2.1.4
    - dvclive==0.11.0
    - pyhmmer==0.8.0

