name: learn2thermDB
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - biopython=1.79
  - dask=2022.2.1
  - dask-core=2022.2.1
  - dask-jobqueue=0.8.1
  - distributed=2022.2.1
  - joblib
  - dvc=2.27.2
  - dvc-data=0.10.0
  - dvc-http=2.19.1
  - dvc-objects=0.4.0
  - dvc-render=0.0.11
  - dvc-ssh=2.19.0
  - dvc-task=0.1.2
  - filelock=3.8.0
  - matplotlib=3.6.0
  - pandas=1.5.0
  - python=3.10.6
  - pyyaml=6.0
  - seaborn
  - matplotlib
  - blast
  - diamond
  - pyarrow
  - fastparquet
  - pip
  - pip:
    - duckdb==0.7.0
    - codecarbon==2.1.4
    - dvclive==0.11.0

