stages:
  get_ecoli:
    wdir: ../
    cmd: python ./analysis_pipeline/t0.1a_get_all_ecoli.py
    deps:
    - ./data/uniprot/uniprot_pulled_timestamp
    - ./analysis_pipeline/t0.1a_get_all_ecoli.py
    outs:
    - ./data/uniprot/uniprot_ecoli.xml
    metrics:
    - ./data/metrics/t0.1a_metrics.yaml:
        cache: false
  full_protein_search_space:
    wdir: ../
    cmd: python ./analysis_pipeline/t0.2_full_protein_search_space.py
    deps:
    - ./data/taxa.parquet
    - ./data/metrics/s0.2_protein_per_data_distr.csv
    - ./analysis_pipeline/t0.2_full_protein_search_space.py
    metrics:
    - ./data/metrics/t0.2_total_search_space.csv:
        cache: false
    plots:
    - ./data/plots/total_search_space.png:
        cache: false
    - ./data/plots/cumsum_proteins.png:
        cache: false
  chosen_protein_search_space:
    wdir: ../
    cmd: python ./analysis_pipeline/t1.0_chosen_protein_search_space.py
    deps:
    - ./data/taxa_thermophile_labels.parquet
    - ./data/metrics/s0.2_protein_per_data_distr.csv
    - ./analysis_pipeline/t1.0_chosen_protein_search_space.py
    metrics:
    - ./data/metrics/t1.0_chosen_protein_search_space.yaml:
        cache: false
    plots:
    - ./data/plots/protein_per_taxa_hist.png:
        cache: false

  protein_alignment_resource_test:
    wdir: ../
    cmd: python ./analysis_pipeline/t1.4_protein_alignment_resource_test.py
    deps:
    - ./analysis_pipeline/t1.4_protein_alignment_resource_test.py
    - ./learn2therm/utils.py
    - ./learn2therm/blast.py
    - ./data/taxa_pairs/pair_labels.csv
    - ./data/taxa/proteins/
    - ./data/taxa_pairs/pairwise_16s_blast.csv
    params:
    - get_protein_blast_scores.dask_cluster_class
    - get_protein_blast_scores.max_protein_length
    - get_protein_blast_scores.method
    - get_protein_blast_scores.n_jobs
    - get_protein_blast_scores.method_blast_params
    - get_protein_blast_scores.method_diamond_params
    - get_protein_blast_scores.blast_metrics
    metrics:
    - ./data/metrics/t1.4_metrics.yaml:
        cache: false
  protein_alignment_blast_dia_compare:
    wdir: ../
    cmd: python ./analysis_pipeline/t1.5_protein_alignment_hits_blast_vs_diamond.py
    deps:
    - ./analysis_pipeline/t1.5_protein_alignment_hits_blast_vs_diamond.py
    - ./learn2therm/utils.py
    - ./learn2therm/blast.py
    - ./data/taxa_pairs/pair_labels.csv
    - ./data/taxa/proteins/
    - ./data/taxa_pairs/pairwise_16s_blast.csv
    params:
    - get_protein_blast_scores.dask_cluster_class
    - get_protein_blast_scores.max_protein_length
    - get_protein_blast_scores.n_jobs
    - get_protein_blast_scores.method_blast_params
    - get_protein_blast_scores.method_diamond_params
    - get_protein_blast_scores.blast_metrics
    outs:
    - ./data/analysis/blast_vs_diamond_hits.csv