logging:
  version: 1
  handlers:
    file:
      class: logging.handlers.RotatingFileHandler
      filename: ./logs/dask/dask.log
      level: INFO
  loggers:
    distributed.worker:
      level: INFO
      handlers:
        - file
    distributed.scheduler:
      level: INFO
      handlers:
        - file
    distributed.client:
      level: INFO
      handlers:
        - file
